### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by zarzen** [mli/d2l-tvm#35]
https://github.com/d2l-ai/d2l-tvm/blob/master/chapter_expressions/index_shape_expressions.md
```
p, q = te.var('p'), te.var('q')
B = te.compute((p, q), lambda i, j: A[(i*q+j)//m, (i*q+j)%m], name='b')
```
`m` should be `p`

**Comment by yidawang** [comment]
Please submit a PR to fix it. Thanks! @zarzen

**Comment by Ca0L** [comment]
I think `A[(i*q+j)//m, (i*q+j)%m]` is correct since elements are taken from `A` whose shape is `(n, m)`. The index in the square bracket should be relative to `A`.

**Comment by yidawang** [comment]
@Ca0L Yes, you are right. Thanks for pointing it out.
@zarzen Can you double check and send another PR to revert the change if you agree with @Ca0L ? Sorry for the confusion.

**Comment by zarzen** [comment]
sorry for the confusion, I am wrong. @Ca0L Thanks for correcting!
